// Package capcom implements the Capsule Communicator controller.
//
// CAPCOM performs template rendering only — reads signals.jsonl and
// step-plan.json, produces LANDED.md content as the RELAY signal reason.
// RELAY signal — never blocks, never gates.
package capcom

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/taem-dev/taem/internal/controller"
)

// signalEntry represents a single signal from signals.jsonl.
type signalEntry struct {
	Controller  string   `json:"controller"`
	SignalValue string   `json:"signal"`
	Reason      string   `json:"reason"`
	Evidence    []string `json:"evidence"`
}

// planEntry represents the step-plan.json structure.
type planEntry struct {
	MissionID string `json:"mission_id"`
	Steps     []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"steps"`
	Order []string `json:"order"`
}

// Controller implements the CAPCOM (Capsule Communicator) deterministic controller.
type Controller struct {
	// Now is injectable for testing. Defaults to time.Now.
	Now func() time.Time
}

// New returns a new CAPCOM controller instance.
func New() *Controller {
	return &Controller{Now: time.Now}
}

// Name returns the controller callsign.
func (c *Controller) Name() string {
	return "CAPCOM"
}

// Mode returns ModeDeterministic per ADR-005.
func (c *Controller) Mode() controller.ControllerMode {
	return controller.ModeDeterministic
}

// Run renders the LANDED.md template from signals and step-plan data.
//
// Always returns a RELAY signal — non-blocking, never gates.
func (c *Controller) Run(ctx context.Context, inputs controller.Inputs) (controller.Signal, error) {
	select {
	case <-ctx.Done():
		return controller.Signal{}, ctx.Err()
	default:
	}

	var signals []signalEntry
	var plan planEntry

	// Read signals.jsonl.
	if inputs.ManifestPath != "" {
		sigFile := filepath.Join(inputs.ManifestPath, "signals.jsonl")
		data, err := os.ReadFile(sigFile)
		if err == nil {
			lines := strings.Split(strings.TrimSpace(string(data)), "\n")
			for _, line := range lines {
				line = strings.TrimSpace(line)
				if line == "" {
					continue
				}
				var entry signalEntry
				if json.Unmarshal([]byte(line), &entry) == nil {
					signals = append(signals, entry)
				}
			}
		}
	}

	// Read step-plan.json.
	if inputs.StepPlan != "" {
		data, err := os.ReadFile(inputs.StepPlan)
		if err == nil {
			json.Unmarshal(data, &plan)
		}
	}

	select {
	case <-ctx.Done():
		return controller.Signal{}, ctx.Err()
	default:
	}

	// Render LANDED.md content.
	now := c.Now()
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# LANDED — Mission %s\n\n", inputs.MissionID))
	sb.WriteString(fmt.Sprintf("**Completed:** %s\n\n", now.UTC().Format(time.RFC3339)))

	sb.WriteString("## Signal Summary\n\n")
	sb.WriteString("| Controller | Signal | Reason |\n")
	sb.WriteString("|---|---|---|\n")
	goCount := 0
	noGoCount := 0
	for _, sig := range signals {
		sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", sig.Controller, sig.SignalValue, sig.Reason))
		switch sig.SignalValue {
		case "GO":
			goCount++
		case "NO-GO":
			noGoCount++
		}
	}
	sb.WriteString("\n")

	if len(plan.Order) > 0 {
		sb.WriteString("## Step Plan\n\n")
		for i, stepID := range plan.Order {
			sb.WriteString(fmt.Sprintf("%d. %s\n", i+1, stepID))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("---\n*Generated by CAPCOM at %s*\n", now.UTC().Format(time.RFC3339)))

	content := sb.String()

	evidence := []string{
		fmt.Sprintf("signals_read=%d", len(signals)),
		fmt.Sprintf("go_signals=%d", goCount),
		fmt.Sprintf("nogo_signals=%d", noGoCount),
		fmt.Sprintf("steps=%d", len(plan.Order)),
		fmt.Sprintf("rendered_bytes=%d", len(content)),
	}

	return controller.Signal{
		Controller:  "CAPCOM",
		SignalValue: "RELAY",
		Reason:      content,
		Evidence:    evidence,
	}, nil
}
